name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python Dependencies
      run: pip install numpy matplotlib

    - name: Install C dependencies
      run: sudo apt-get install -y gcc

    - name: Compile QAM4.c
      run: gcc QAM4.c -o qam4 -lm

    - name: Compile QAM16.c
      run: gcc QAM16.c -o qam16 -lm

     - name: Run QAM4
      run: echo "Hello World!" | ./qam4
    
    - name: Run QAM16
      run: echo "Hello World!" | ./qam16

    - name: Run Python QAM4 Script
      run: echo "Hello World!" | python QAM4.py
    
    - name: Run Python QAM16 Script
      run: echo "Hello World!" | python QAM16.py
