name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y gcc

    - name: Compile QAM4.c
      run: gcc QAM4.c -o qam4 -lm

    - name: Compile QAM16.c
      run: gcc QAM16.c -o qam16 -lm

    - name: Compile modulator.c
      run: gcc modulator.c -o modulator -lm

    - name: Compile demodulator.c
      run: gcc demodulator.c -o demodulator -lm

    - name: Run QAM4
      run: ./qam4

    - name: Run QAM16
      run: ./qam16

    - name: Run modulator
      run: ./modulator
      
    - name: Run demodulator
      run: ./demodulator
